### ISSUE TITLE
RickRoll function has "potentionaly" dangerous link

### ISSUE THREAD

**Issue by 4nn0nym05** [perplexityjeff/PowerShell-Troll#4]
Function Send-RickRoll 
{
    Invoke-Expression (New-Object Net.WebClient).DownloadString("http://bit.ly/e0Mw9w")
}

"http://bit.ly/e0Mw9w" Defender flags it as Trojan also Virus total has some detection on it https://www.virustotal.com/gui/url/6694e310b765140aa67ce40366948d0a3edc2569a3989fbb41cbebf6fe91e7de/detection

Just giving you heads up

**Comment by perplexityjeff** [comment]
Thanks for the heads up, I do believe the URL is still valid though. The contents are not a virus but I believe that because there is  encoded data in the script it could get flagged. 

The URL redirects to https://www.leeholmes.com/projects/ps_html5/Invoke-PSHtml5.ps1 also see https://www.leeholmes.com/about/.

I'll change it to not use the bit.ly so it makes it a bit more transparent for people.
